# This is a basic workflow to help you get started with Actions

name: Getting Started

# Controls when the workflow will run
on:
 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo what is this directory
          ls -a
          echo
          echo is java installed?
          java -version
          echo
          echo is git installed?
          git --version
          echo what is the build tools?
          mvn -version
          gradle -version
          ant -version
          echo
          echi Whre is the Android SDK root?
          echo $ANDROID_SDK_ROOT
          echo
          echo Where are the Selenium jars?
          echo $SELENIUM_JAR-PATH
          echo
          echo Who is running this script?
          whoami
          echo
          echo How is the disk lied out? 
          df
          echo 
          echo What envornment variable are availabele?
          env
