name: Github actions Maven build
on:
  push:
    branches: [ master ]
jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:
    - name: Step 1 - checkout manin branch
      uses: actions/checkout@v1
     
    - name: Step 2 - Setup JDK
      uses: actions/setup-java@v1
      with:
       java-version: 1.8
       
    - name: Step 3 - Maven build
      run: mvn -B package --file pom.xml
     
    - name: Step 4 - List the current directory
      run: ls -a
     
    - name: Step 5 - list the target directory
      run: |
       cd target
       ls -a
